# 1. Server Config
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

# 3. Log Level
logging:
  level:
    root: info   #  error < info < debug